### ISSUE TITLE
Setup Home Assistant & Home Server

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/my-smart-home#1]
## Tasks

- [x] Network setup #14 
- [x] Get Linux server going and Ansibled
- [x] Clone repository on Linux
- [x] Document...
- [ ] Clone my-smart-home
- [ ] Run docker-compose

**Comment by ZinkNotTheMetal** [comment]
Steps

- [ ] Create Ansible host on Synology VM
- [ ] Setup VM
- [ ] sudo apt update
- [ ] Install ansible
- [ ] Install git
- [ ] clone home-server-configuration repository
