### ISSUE TITLE
Setup network w/ Unifi equipment

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/my-smart-home#14]
### Description

Add Network to Home Assistant

## Tasks

- [x] Purchased
- [x] Installed
- [x] Online!
- [ ] #86

## Network setup tasks

- [X] Setup in Unifi app & configure basics
- [x] Change SSH password
- [X] Switch Wi-Fi name
- [X] Add guest network
- [X] Limit guest network speeds
- [X] Switch Subnets for different workload
- [x] Add wireless networks & hide SSID
- [ ] Add networking for docker VLAN3

### Integration URL

https://www.home-assistant.io/integrations/unifi/

### New Hardware?

Yes

### Add Amazon / store URL for referencing if new hardware is required

- [x] [Unifi - Dream Machine Pro](https://store.ui.com/us/en/products/udm-pro)
- [x] [Networking Rack](https://store.ui.com/us/en/pro/category/all-accessories/products/toolless-mini-rack)
- [x] [Wireless APs](https://store.ui.com/us/en/pro/category/all-wifi/products/u6-plus)
- [x] [Power Distribution Pro](https://store.ui.com/us/en/pro/category/all-power-tech/products/usp-pdu-pro)

## Resources

- [Setting up VLAN separation with Unifi](https://vninja.net/2019/08/08/creating-isolated-networks-ubiquiti/)
- [Supporting article for VLAN separation](https://roen.us/article/networking/secure-iot-unifi/)

**Comment by ZinkNotTheMetal** [comment]
I decided to go with a Unifi rack and some additional systems to make sure that the internet was extremely reliable and was able to controlled remotely

**Comment by ZinkNotTheMetal** [comment]
## Remaining Tasks

- [ ] Switch Wi-Fi name
- [ ] Add guest network
- [ ] Switch Subnets for different workload
- [ ] Add networking for docker VLAN3
- [ ] Integrate with Home Assistant
