### ISSUE TITLE
[HA-Integration]: Fireplace

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/my-smart-home#31]
### Description

- [ ] Research RF -> WiFi
- [ ] Get that system setup and integrated

### Automation Idea

- [ ] Turn on when cold

### New Hardware?

Yes

**Comment by ZinkNotTheMetal** [comment]
## Tasks

- [ ] Research RF -> Wifi
- [ ] Figure out where I'm going to put the device
