### ISSUE TITLE
[HA-Integration]: DuckDNS / DNS

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/my-smart-home#50]
## Tasks

- [x] #14 
- [x] #1 
- [ ] Determine if buying a domain?
- [ ] Setup DuckDNS integration / docker on Linux
- [ ] Ensure that the IP is updated (instance running no issues)

### New Hardware?

No

**Comment by ZinkNotTheMetal** [comment]
https://community.ui.com/questions/Where-do-I-set-DNS/63161399-a2dd-404c-9f32-0c27db6ef0f7
