### ISSUE TITLE
[HA-Integration]: Brother Printer

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/my-smart-home#73]
### Description

Add the printer to Home Assistant

### Tasks

- [x] Purchased
- [x] Installed
- [x] Setup
- [x] Integrated

### Integration URL

https://www.home-assistant.io/integrations/brother/

### Automation Idea

Get notifications

- [ ] Out of paper
- [ ] Jammed
- [ ] Out of ink
- [ ] Low on ink

### New Hardware?

Yes

### Add Amazon / store URL for referencing if new hardware is required

https://www.amazon.com/dp/B092YN1JK5/ref=cm_sw_r_as_gl_api_gl_i_TAF49MBZ9ZP05CKTMN93?linkCode=ml2&tag=williamdzink-20

**Comment by ZinkNotTheMetal** [comment]
Done
